MvcOnlineTicariOtomasyon/Controllers/qrcodeController.cs
using QRCoder;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class qrcodeController : Controller
    {
        // GET: qrcode
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string code)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                QRCodeGenerator qr = new QRCodeGenerator();
                QRCodeGenerator.QRCode carecode = qr.CreateQrCode(code, QRCodeGenerator.ECCLevel.Q);

                using (Bitmap image = carecode.GetGraphic(10))
                {
                    image.Save(ms,ImageFormat.Png);
                    ViewBag .carecodeimage="data:image/png;base64,"+Convert.ToBase64String(ms.ToArray());
                }
            }
            return View();

        }
    }
}

MvcOnlineTicariOtomasyon/Views/qrcode/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<div>

    @using (Html.BeginForm("Index", "qrcode", FormMethod.Post))
            {
                <input type="text"name="code" class="form-control"/><br />
                <button class="btn btn-success form-control" type="submit" >Create</button>

            }
    <br />
    @if (ViewBag.carecodeimage != null)
            {
                <img src="@ViewBag.carecodeimage" alt="" style="width:400px;height:400px;" />
            }
</div>