MvcOnlineTicariOtomasyon/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.classes;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class StatisticsController : Controller
    {
        // GET: Statistics
        Context c = new Context();
        public ActionResult Index()
        {
            var count = c.Carilers.Count().ToString();
            ViewBag.d1=count;
            var numberp=c.Products.Count().ToString();
            ViewBag.d2=numberp;
            var numberpersonel = c.Personels.Count().ToString();
            ViewBag.d3 = numberpersonel;
            var numbercategory = c.Categorys.Count().ToString();
            ViewBag.d4 = numbercategory;
            var numberstock = c.Products.Sum(x=>x.Stock).ToString();
            ViewBag.d5 = numberstock;
            var numberbrand =(from x in c.Products select x.Brand).Distinct().Count().ToString();
            ViewBag.d6 = numberbrand;
            var crirtic= c.Products.Count(x=>x.Stock<=20).ToString();
            ViewBag.d7= crirtic;
            var maxprice = (from x in c.Products orderby x.SalesPrice descending select x.ProductName).FirstOrDefault();
            ViewBag.d8 = maxprice;
            var minprice = (from x in c.Products orderby x.SalesPrice ascending select x.ProductName).FirstOrDefault();
            ViewBag.d9 = minprice;
            var maxbrand =c.Products.GroupBy(x=>x.Brand).OrderByDescending(c=>c.Count()).Select(x=>x.Key).FirstOrDefault();
            ViewBag.d10 = maxbrand;
            var numref = c.Products.Count(x=>x.ProductName=="Buzdolabı").ToString();
            ViewBag.d11 = numref;
            var numlaptop = c.Products.Count(x => x.ProductName == "Laptop").ToString();
            ViewBag.d12 = numlaptop;
            var bestseller= c.Products.Where(x=>x.ProductId ==(c.SalesMoves.GroupBy(a=>a.ProductId).OrderByDescending(z=>z.Count()).Select(y=>y.Key)).FirstOrDefault()).Select(x=>x.ProductName).FirstOrDefault();
            ViewBag.d13= bestseller;
            var total= c.SalesMoves.Sum(x=>x.Amount).ToString();
            ViewBag.d14 = total;
            DateTime today = DateTime.Today ;
            var totalsale= c.SalesMoves.Count(x=> x.Date ==today).ToString();
            ViewBag.d15 = totalsale;
            var todaystotal = 0;
            try
            {
                 todaystotal = (from x in c.SalesMoves where x.Date == today select x.Amount).Sum();
            }
            catch
            {
                 todaystotal = 0;
            }

            
                //c.SalesMoves.Where(a=>a.Date==today).Sum(x => x.Amount).ToString();
            ViewBag.d16 = todaystotal.ToString();
            return View();
        }

        public ActionResult SimpleTables()
        {

            var sorgu = from x in c.Carilers
                        group x by x.CariCity into g
                        select new ClassGrup
                        {
                            City = g.Key,
                            Count = g.Count()
                        };

            return View(sorgu.ToList());
        }
        public PartialViewResult p1()
        {
            var sorgu2 = from x in c.Personels
                         group x by x.Department.DepartmentName into g
                         select new ClassGrup2
                         {
                             Department = g.Key,
                             Count = g.Count()
                         };
            return PartialView(sorgu2.ToList());
        }
        public PartialViewResult p2()
        {
            var sorgu2 = c.Carilers.ToList();
            return PartialView(sorgu2);
        }
        public PartialViewResult p3()
        {
            var sorgu2 = c.Products.ToList();
            return PartialView(sorgu2);
        }
        public PartialViewResult p4()
        {
            var sorgu3= from x in c.Products
                         group x by x.Brand into g
                         select new ClassGrup3
                         {
                             Brand = g.Key,
                             Count = g.Count()
                         };
            return PartialView(sorgu3.ToList());
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Statistics/Index.cshtml
@{
    ViewBag.Title = "Index";
}


<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>

    <!-- Custom Theme files -->
    <link href="~/web/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <script src="~/web/web2/js/zingchart.min.js"></script>
    <script src="~/web/web2/js/zingchart.jquery.js"></script>
    <script src="~/web/web2/js/jquery.easydropdown.js"></script>
    <script src="~/web/web2js/jquery.nicescroll.js"></script>

    <link href="~/web/web2css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />


    <script src="~/web/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>

    <link href="~/web/web2/css/nav.css" rel="stylesheet" type="text/css" media="all" />
    <script src="~/web/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Cari</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">

                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Number of Products</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">

                <div class="icon-text">
                    <h3>@ViewBag.d3</h3>
                    <p>Number of Personel</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">

                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Number of Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Total Stock</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">

                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Number of Brand</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">

                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Critical Level</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">

                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Max Priced Product</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>


    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f1c40f">
                <div class="icon-text">
                    <h3>@ViewBag.d9</h3>
                    <p>Min Priced Product</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#e67e22">

                <div class="icon-text">
                    <h3>@ViewBag.d10</h3>
                    <p>Max Brand</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#e74c3c">

                <div class="icon-text">
                    <h3>@ViewBag.d11</h3>
                    <p>Number of Refrigerator</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#95a5a6">

                <div class="icon-text">
                    <h3>@ViewBag.d12</h3>
                    <p>Number of laptop</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#f39c12">
                <div class="icon-text">
                    <h3>@ViewBag.d13</h3>
                    <p>Best Seller</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#d35400">

                <div class="icon-text">
                    <h3>@ViewBag.d14 ₺</h3>
                    <p>Total Amount</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#c0392b">

                <div class="icon-text">
                    <h3>@ViewBag.d15 ₺</h3>
                    <p>Today's Sales</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#7f8c8d">

                <div class="icon-text">
                    <h3>@ViewBag.d16 ₺</h3>
                    <p>Today's Total</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

MvcOnlineTicariOtomasyon/Views/Statistics/SimpleTables.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.classes.ClassGrup>

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/web/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">



        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Simple Tables</h1>
                    </div>
                  
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Category Table</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>Task</th>
                                            <th>Progress</th>
                                            <th style="width: 40px">Label</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1.</td>
                                            <td>Telefon</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-danger">55%</span></td>
                                        </tr>
                                        <tr>
                                            <td>2.</td>
                                            <td>Küçük Ev Aletleri</td>
                                            <td>
                                                <div class="progress progress-xs">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>3.</td>
                                            <td>Bilgisayar</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-primary" style="width: 30%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-primary">30%</span></td>
                                        </tr>
                                        <tr>
                                            <td>4.</td>
                                            <td>Deneme</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-warning">70%</span></td>
                                        </tr>
                                        <tr>
                                            <td>5.</td>
                                            <td>Beyaz Eşya</td>
                                            <td>
                                                <div class="progress progress-xs progress-striped active">
                                                    <div class="progress-bar bg-success" style="width: 90%"></div>
                                                </div>
                                            </td>
                                            <td><span class="badge bg-success">90%</span></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->

                        </div>
                        <!-- /.card -->
                        @Html.Action("p1", "Statistics")


                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Cari City Table</h3>

                            </div>
                            <!-- /.card-header -->
                            <div class="card-body p-0">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th style="width: 10px">#</th>
                                            <th>City</th>
                                            <th>Progress</th>
                                            <th style="width: 40px">Count</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @{ int sırano = 0;}
                                        @foreach (var item in Model)
                                        {

                                            <tr>
                                                <td>@{sırano++;} @sırano</td>
                                                <td>@item.City</td>
                                                @if (item.Count >= 1 && item.Count <= 3)
                                                {
                                                    <td>
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                                        </div>
                                                    </td>

                                                }
                                                @if (item.Count > 3 && item.Count <= 5)
                                                {
                                                    <td>
                                                        <div class="progress progress-xs">
                                                            <div class="progress-bar bg-warning" style="width: 70%"></div>
                                                        </div>
                                                    </td>

                                                }
                                                @if (item.Count >= 6)
                                                {
                                                    <td>
                                                        <div class="progress progress-xs progress-striped active">
                                                            <div class="progress-bar bg-success" style="width: 90%"></div>
                                                        </div>
                                                    </td>

                                                }
                                                <td>
                                                    @if (item.Count >= 1 &&item.Count<=3)
                                                    {<span class="badge bg-danger">@item.Count</span>}
                                                    @if (item.Count >3 &&item.Count<=5)
                                                    {<span class="badge bg-warning">@item.Count</span>}
                                                    @if (item.Count >= 6)
                                                    {<span class="badge bg-success">@item.Count</span>}
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                        @Html.Action("p4", "Statistics")

                        <!-- /.card -->
                    </div>
                    <!-- /.col -->
                </div>
                <!-- /.row -->
                <div class="row">

                </div>
                @Html.Action("p2", "Statistics")


                <!-- /.row -->
                @Html.Action("p3", "Statistics")
                <!-- /.row -->
            </div><!-- /.container-fluid -->
        </section>
        <!-- /.content -->
        <!-- /.content-wrapper -->
        
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="../../dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="../../dist/js/demo.js"></script>
</body>
</html>

MvcOnlineTicariOtomasyon/Views/Statistics/p1.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.classes.ClassGrup2>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Personel Department Table</h3>

        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Department</th>
                        <th>Progress</th>
                        <th style="width: 40px">Count</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int sırano = 0;}
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@{sırano++;} @sırano</td>
                            <td>@item.Department</td>
                            @if (item.Count == 1)
                            {
                                <td>
                                    <div class="progress progress-xs">
                                        <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                                    </div>
                                </td>

                            }
                            @if (item.Count == 2)
                            {
                                <td>
                                    <div class="progress progress-xs">
                                        <div class="progress-bar bg-warning" style="width: 70%"></div>
                                    </div>
                                </td>

                            }
                            @if (item.Count >= 3)
                            {
                                <td>
                                    <div class="progress progress-xs progress-striped active">
                                        <div class="progress-bar bg-success" style="width: 90%"></div>
                                    </div>
                                </td>

                            }
                            <td>
                                @if (item.Count == 1)
                                {<span class="badge bg-danger">@item.Count</span>}
                                @if (item.Count == 2)
                                {<span class="badge bg-warning">@item.Count</span>}
                                @if (item.Count >= 3)
                                {<span class="badge bg-success">@item.Count</span>}
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->

   

MvcOnlineTicariOtomasyon/Views/Statistics/p2.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.classes.Cariler>

<div class="col-12">
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Cariler Hover Table</h3>

            <div class="card-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                    <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                    <div class="input-group-append">
                        <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body table-responsive p-0">
            <table class="table table-hover text-nowrap">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Surname</th>
                        <th>City</th>
                        <th>Mail</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {

                        <tr>
                            <td>@item.CariId</td>
                            <td>@item.CariName</td>
                            <td>@item.CariSurname</td>
                            <td>@item.CariCity</td>
                            <td>@item.CariMail</td>
                            
                        </tr>
                    }

                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->
</div>

MvcOnlineTicariOtomasyon/Views/Statistics/p3.cshtml
@model IEnumerable<MvcOnlineTicariOtomasyon.Models.classes.Product>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Product Header Table</h3>

                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                        <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0" style="height: 300px;">
                <table class="table table-head-fixed text-nowrap">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Brand</th>
                            <th>Purchase Price</th>
                            <th>Sales Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach(var item in Model)
                        {


                        <tr>

                            <td>@item.ProductId</td>
                            <td>@item.ProductName</td>
                            <td>@item.Stock</td>
                            <td>@item.Purchaseprice</td>
                            <td>@item.SalesPrice</td>
                            
                        </tr>
                        }
                       
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>